version: '3.5'

services:

  jetty:
    image: docker-registry.it.csiro.au/idc/geonetwork:base
    networks:
      - traefik-net
    volumes:
      - .:/usr/src
      - ./m2:/root/.m2
    working_dir: /usr/src
    command: ["mvn", "clean", "install", "-DskipTests"]
    deploy:
        replicas: 1
        labels:
          traefik.frontend.rule: Host:geonetwork.localhost
          traefik.port: 8080
          traefik.docker.network: swarm-infra_traefik-net

networks:
  traefik-net:
    external: true
    name: swarm-infra_traefik-net
