version: '3.5'

networks:
  proxy:
    external: true

# GeoNetwork is heavily hard-coded to be served at localhost:8080/geonetwork. This means it's really difficult to route
# it anywhere on the swarm other than the root route. I.e, PathPrefix needs to be set to / for the Traefik frontend rule
services:
  jetty:
    networks:
      - proxy
    deploy:
        replicas: 1
        labels:
          - traefik.frontend.rule=PathPrefix:/
          - traefik.docker.network=proxy
          - traefik.port=8080
          - traefik.enable=true
