version: '3.5'

networks:
  proxy:
    external: true

services:
  jetty:
    networks:
      - proxy
    deploy:
        replicas: 1
        labels:
          - traefik.frontend.rule=PathPrefixStrip:/core-geonetwork
          - traefik.docker.network=proxy
          - traefik.port=80
          - traefik.enable=true
