version: '3.5'

services:

  jetty:
    networks:
      - traefik-net
    deploy:
        replicas: 1
        labels:
          traefik.frontend.rule: Host:geonetwork.localhost
          traefik.port: 8080
          traefik.docker.network: swarm-infra_traefik-net

networks:
  traefik-net:
    external: true
    name: swarm-infra_traefik-net
